### ISSUE TITLE
Improvement Opportunities

### ISSUE THREAD

**Issue by RomanMunar** [zhouhua/obsidian-power-mode#6]
I really like this plugin especially when shake timer is set to 300 -- keeps me focused. 

1. The `Combo` counter is only being displayed on the first tab. Expectation: Should display on whatever tab you are typing on.
2. The `Rift` effect is overpowering which blocks word-worth width. Solution: Add Opacity setting for the effect.
3. An `Effect` testing textarea in the settings page. or set a flexbox'd demos of the effects.
4. Ability to add a Custom effect.

**Comment by zhouhua** [comment]
Regarding the first point, that was my oversight. It will be fixed in future versions.

Regarding the second and fourth points, I originally planned to allow adding custom effects. However, due to the limited feedback I've received on this plugin, I'm uncertain about the necessity of this feature, so I haven't spent time on it. I think that allowing custom effects would naturally support fine-tuning the current preset effects, such as adjusting the transparency of the `Rift` effect.

Regarding the third point, I haven't implemented similar preview effects in other Obsidian plugin settings interfaces, and the implementation cost is relatively high. Therefore, I will assign a lower priority to this task.

**Comment by RomanMunar** [comment]
There should also be add a command to disable power mode. Kinda tedious to go back and forth in the settings and search for it there and click the on/off button.

**Comment by zhouhua** [comment]
I have released a new version that fixes almost all issues except for the third point.

**Comment by RomanMunar** [comment]
please make active and deactive command into a single `Toggle Power Mode` command. 
btw, the plugin breaks when you click `advanced settings` in the settings page.

**Comment by zhouhua** [comment]
Sorry. The `advanced settings` had a bug when first enabled, which I didn't notice during development. I have released a new version to fix this issue.

I'm not sure how `Toggle` should work because Power Mode is divided into three independent features: "screen shake", "combo" and "cursor explosion" each of which can be enabled or disabled individually. Currently, the active and deactivate commands enable or disable all three features simultaneously.
